# Generated by Django 4.2.1 on 2023-06-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('release_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lte_exists', models.CharField(max_length=50)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
